### ISSUE TITLE
not enough memory

### ISSUE THREAD

**Issue by lcuyh** [alecwangcq/show-attend-and-tell#1]
OS: Ubuntu16.04 64bit
Pytorch: 0.4
RAM: 192GB
Thank you for your code! When i run extract_feature.py, I got error.
"RuntimeError: $ Torch: not enough memory: you tried to allocate 123GB. Buy new RAM!"
How many memory for you extract feature form the coco dataset? By the way, what kind of GPU you used in the code? I see you used 3 GPU, so i would like to know the detail about the GPU memory.

**Comment by alecwangcq** [comment]
As far as I can remember, I used 3 16GB GPUs, and the RAM is 128GB. 
So, I think you can use a smaller batch size, say 32 or 64, if with 1 GPU . 192GB RAM is definitely enough. Check if there are other processes consumed too much memory.

**Comment by lcuyh** [comment]
Hi! Thank you for your promptly reply! I debug the code and I found the reason. The two list in function extract_features is two big. Before torch.cat(features, 0), imnames, the memory cost is about 128G. So when the function run torch.cat(), it got memory error. This is test on COCO 2014 train dataset. Due to the small size of validation dataset, the feature extract is 65 GB. When you run this code, do you use so big memory?
