### ISSUE TITLE
RuntimeError: invalid argument 0: Tensors must have same number of dimensions: got 2 and 3

### ISSUE THREAD

**Issue by lcuyh** [alecwangcq/show-attend-and-tell#2]
Hi! When i run main.py, i got the RuntimeError. I debug the code and found the error was caused by the different tensor shape of the feas and words. After extracting feature maps, the size of the features map is (512, 14, 14). So it is different from the size of the words(128, 512)(The size of the tensor features is 128, 512, 14, 14). How to deal with the error? Can you give some suggestions or advice?

**Comment by alecwangcq** [comment]
you can simply reshape the feature map from (512, 14, 14) to (196, 512) by
`f = f.view(512, 196).transpose(1, 0).contiguous()` 
in the data loader.  
Or, convert the extracted features to the shape of (196, 512) and store them. (128 is the batch size)

after attention, the feature map will be mapped to a vector, whose dimension of 512.
