### ISSUE TITLE
KeyError: tensor(4)

### ISSUE THREAD

**Issue by lcuyh** [alecwangcq/show-attend-and-tell#3]
Hi! Thank you for sharing your code! When i run the visualize jupter notebook, i got an error. 
KeyError: tensor(4)
KeyError                                  Traceback (most recent call last)
<ipython-input-7-1562e1c318d1> in <module>()
      1 alps = torch.cat(alphas[idx][1:], 0)
----> 2 cap = decode_captions(captions[idx].data.cpu().view(1, -1), vocab.idx2word)[0]
File "./utils/helper.py", line 16, in devode_captions
      word = idx_to_word[captions[idx, wid]]
How to solve this problems?
By the way, i can not understand the code of the __attention__layer in models.py. I confused by the code
'att_full = nn.ReLU()(att_fea + att_h + self.att_bias.view(1, -1, 1))'. i saw the example code of the nn.ReLU(). So what the meaning of '(att_fea + att_h + self.att_bias.view(1, -1, 1))' after nn.ReLU(). Can you explain it?

**Comment by alecwangcq** [comment]
Are you using pytorch 0.4.0? The code was only tested with pytorch 0.2.0

It is used to compute the attention weights of each channel. i.e.

**Comment by lcuyh** [comment]
Yes! I use Pytorch 0.4.0 and python3. So i need to change a lot.

**Comment by RodinIvan** [comment]
@lcuyh have you succeed in moving code to Pytorch 0.4.0? 
I'm having just the same issues that you described now, and it would be great if you could share your code somehow
